version: '3.8'

services:
  kenjix-app:
    build: .
    container_name: kenjix_security
    ports:
      - "81:81"
    environment:
      MYSQL_HOST: database-1.ca3mcqac2tzz.us-east-1.rds.amazonaws.com
      MYSQL_PORT: 3306
      MYSQL_DATABASE_KENJIX: estoque
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: K0t0net#g4
      SPRING_FLYWAY_ENABLED: "false"
    restart: always