version: '3.8'

services:
  kenjix-app:
    build: .
    container_name: kenjix_security
    ports:
      - "7020:7020"
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE_KENJIX: ${MYSQL_DATABASE_KENJIX}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      SPRING_FLYWAY_ENABLED: "false"
    restart: always