server:
  port: 81

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000

spring:
  application:
    name: kenjix_security

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE_KENJIX}?useTimezone=true&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_ROOT_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false